
   
version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    volumes:
      - ./infra-data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=book_changelog_user
      - POSTGRES_PASSWORD=book_changelog_password
      - POSTGRES_DB=book_changelog_db
    ports:
      - 5432:5432

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgres
    command: postgres:5432
    environment:
      - TIMEOUT_LENGTH=30